### ISSUE TITLE
CPU scheduling

### ISSUE THREAD

**Issue by azenla** [SpinlockLabs/Raptor#3]
CPU scheduling is key to supporting userspace applications, as we must preemptively timeshare the CPU with other applications. The Raptor OS CPU scheduler should be a single tier root scheduler, with a kernel-only task queue running as a scheduled process.

## Tasks
- [x] CPU Scheduler
  - [x] Process API
  - [x] CPU state switching
  - [x] Kernel idle process
  - [x] Userspace processes
- [x] Kernel Task Queue
  - [x] task scheduling
  - [x] queue flush
  - [x] task repeating
