### ISSUE TITLE
IP layer

### ISSUE THREAD

**Issue by azenla** [SpinlockLabs/Raptor#4]
The Internet Protocol layer is integral to supporting any meaningful network interaction. Raptor OS should support both IPv4 and IPv6, and support many different configurations, customizations, interceptions, while ensuring low resource usage and generic security.

## Tasks

- [ ] IPv4
  - [ ] Send
  - [ ] Receive
- [ ] IPv6
  - [ ] Send
  - [ ] Receive
- [ ] Route layer
  - [ ] Local routing table
  - [ ] User routing tables
- [ ] Firewall
  - [ ] Simple firewall rules
