### ISSUE TITLE
Framebuffer subsystem

### ISSUE THREAD

**Issue by azenla** [SpinlockLabs/Raptor#7]
A framebuffer subsystem would provide framebuffer devices for use with VGA on x86 or the BCM framebuffer on ARM.

## Tasks
- [ ] Framebuffer subsystem
  - [x] Read/Write support
  - [ ] Support varying pixel encodings
  - [ ] Resize support
  - [ ] V-Sync support
- [x] Raspberry Pi framebuffer
- [ ] VGA framebuffer
